version: '2'
services:
  app:
    build: .
    ports:
    - "3000:3000"
    environment:
    - MONGO_URL=mongodb://mongo:27017/sample_chat
  mongo:
    image: mongo
    volumes:
    - mongo:/data
volumes:
  mongo: {}